#pragma once

enum class EPACKETMESSAGETYPE : unsigned char {
	EPMT_JOIN,
	EPMT_NEWPLAYER,
	EPMT_UPDATE,
	EPMT_DISCONNECT,
	EPMT_DISCONNECTOTHER,
	EPMT_COUNT
};

enum class EPACKETFAILEDTYPE : unsigned char {
	EPFT_FAILED,
	EPFT_SUCCEED,
	EPFT_EXIST,
	EPFT_COUNT
};

struct GAMEPACKET {
	EPACKETMESSAGETYPE m_MessageType;
	EPACKETFAILEDTYPE m_FailedReason;

public:
	GAMEPACKET() : m_MessageType(EPACKETMESSAGETYPE::EPMT_COUNT), m_FailedReason(EPACKETFAILEDTYPE::EPFT_COUNT) {};

};